services:
  - type: web
    name: student-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard_final:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
